[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "python-docx>=1.1.2",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.3",
]
